<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="geoSets">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="geoSet" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>

                            <!-- main node <internalCode> -->
                            <xs:element name="internalCode" type="xs:string" minOccurs="1" maxOccurs="1"/>

                            <!-- main node <unM49> -->
                            <xs:element name="unM49" type="xs:string" minOccurs="1" maxOccurs="1" nillable="true"/>

                            <!-- main node <tags> -->
                            <xs:element name="tags" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="tag" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <!-- main node <countryCodes> -->
                            <xs:element name="countryCodes" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="cc" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>

                        <xs:attribute name="index" type="xs:string" use="optional"/>

                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>
