/**
 * This file has been automatically generated by the `data-geoCodes` application.
 * Any modifications you make will be overwritten during upgrades.
 * To avoid this, you can save the data directory in another location and launch the app specifying the new directory.
 * If you want to contribute to the development of the data, please follow these steps:
 * - Install Node.js on your system (you can use the instructions at https://nodejs.org/en/download/package-manager).
 * - Clone the repository from GitHub `https://github.com/alibe1971/data-geoCodes`.
 * - Modify the JSON files in the directory.
 * - Run the `node build` script from your terminal.
 * - The built files will be located inside the directory:
 *   - `Data/built/node`
 * - Submit a pull request to publish your changes.
 * - You can also clone the GoLang application, integrate the built data, and submit two separate pull requests:
 *   - One for the data modifications.
 *   - Another for integrating the modified data into the specific app.
 * For further detailed information, please refer to the documentation.
 */

package TranslationsData

import (
	"github.com/alibe1971/go-geoCodes/geoCodes/Data/Translations/en"
	"github.com/alibe1971/go-geoCodes/geoCodes/Data/Translations/it"
)

var TranslationsCountries = map[string]string{
	"en": TranslationsEn.Countries,
	"it": TranslationsIt.Countries,
}

var TranslationsCurrencies = map[string]string{
	"en": TranslationsEn.Currencies,
	"it": TranslationsIt.Currencies,
}

var TranslationsGeoSets = map[string]string{
	"en": TranslationsEn.GeoSets,
	"it": TranslationsIt.GeoSets,
}

var TranslationsLanguages = map[string]string{
	"en": TranslationsEn.Languages,
	"it": TranslationsIt.Languages,
}

