/**
 * This file has been automatically generated by the `data-geoCodes` application.
 * Any modifications you make will be overwritten during upgrades.
 * To avoid this, you can save the data directory in another location and launch the app specifying the new directory.
 * If you want to contribute to the development of the data, please follow these steps:
 * - Install Node.js on your system (you can use the instructions at https://nodejs.org/en/download/package-manager).
 * - Clone the repository from GitHub `https://github.com/alibe1971/data-geoCodes`.
 * - Modify the JSON files in the directory.
 * - Run the `node build` script from your terminal.
 * - The built files will be located inside the directory:
 *   - `Data/built/node`
 * - Submit a pull request to publish your changes.
 * - You can also clone the GoLang application, integrate the built data, and submit two separate pull requests:
 *   - One for the data modifications.
 *   - Another for integrating the modified data into the specific app.
 * For further detailed information, please refer to the documentation.
 */

package geoCodes

const Scripts = `{
    "Adlm": {
        "name": "Adlam",
        "NOTES": []
    },
    "Afak": {
        "name": "Afaka",
        "NOTES": []
    },
    "Aghb": {
        "name": "Albanese caucasico",
        "NOTES": [
            "https://it.wikipedia.org/wiki/Albania_caucasica"
        ]
    },
    "Ahom": {
        "name": "Ahom, Tai Ahom",
        "NOTES": []
    },
    "Arab": {
        "name": "Arabo",
        "NOTES": []
    },
    "Aran": {
        "name": "Arabo (nasta'liq)",
        "NOTES": []
    },
    "Armi": {
        "name": "Aramaico biblico",
        "NOTES": []
    },
    "Armn": {
        "name": "Armeno",
        "NOTES": []
    },
    "Avst": {
        "name": "Avestico",
        "NOTES": [
            "https://it.wikipedia.org/wiki/Lingua_avestica"
        ]
    },
    "Bali": {
        "name": "Balinese",
        "NOTES": []
    },
    "Bamu": {
        "name": "Bamum",
        "NOTES": []
    },
    "Bass": {
        "name": "Bassa Vah",
        "NOTES": []
    },
    "Batk": {
        "name": "Batak",
        "NOTES": []
    },
    "Beng": {
        "name": "Bengalese (Bangla)",
        "NOTES": []
    },
    "Berf": {
        "name": "Beria Erfe",
        "NOTES": []
    },
    "Bhks": {
        "name": "Bhaiksuki",
        "NOTES": []
    },
    "Blis": {
        "name": "Blissymbol",
        "NOTES": []
    },
    "Bopo": {
        "name": "Bopomofo",
        "NOTES": [
            "https://it.wikipedia.org/wiki/Bopomofo"
        ]
    },
    "Brah": {
        "name": "Brahmi",
        "NOTES": []
    },
    "Brai": {
        "name": "Braille",
        "NOTES": []
    },
    "Bugi": {
        "name": "Buginese",
        "NOTES": [
            "https://it.wikipedia.org/wiki/Lingua_buginese"
        ]
    },
    "Buhd": {
        "name": "Buhid",
        "NOTES": []
    },
    "Cakm": {
        "name": "Chakma",
        "NOTES": []
    },
    "Cans": {
        "name": "Sillabario Aborigeno Canadese Unificato",
        "NOTES": [
            "https://it.wikipedia.org/wiki/Sillabario_aborigeno_canadese"
        ]
    },
    "Cari": {
        "name": "Carian",
        "NOTES": []
    },
    "Cham": {
        "name": "Cham",
        "NOTES": []
    },
    "Cher": {
        "name": "Cherokee",
        "NOTES": []
    },
    "Chis": {
        "name": "Chisoi",
        "NOTES": []
    },
    "Chrs": {
        "name": "Corasmiano",
        "NOTES": [
            "https://it.wikipedia.org/wiki/Lingua_corasmia"
        ]
    },
    "Cirt": {
        "name": "Cirth",
        "NOTES": []
    },
    "Copt": {
        "name": "Copto",
        "NOTES": []
    },
    "Cpmn": {
        "name": "Cipro-Minoico",
        "NOTES": []
    },
    "Cprt": {
        "name": "Cipriota",
        "NOTES": []
    },
    "Cyrl": {
        "name": "Cirillico",
        "NOTES": []
    },
    "Cyrs": {
        "name": "Cirillico (slavo ecclesiastico antico)",
        "NOTES": []
    },
    "Deva": {
        "name": "Devanagari (Nagari)",
        "NOTES": [
            "https://it.wikipedia.org/wiki/Alfabeto_devanagari"
        ]
    },
    "Diak": {
        "name": "Akuru dives",
        "NOTES": []
    },
    "Dogr": {
        "name": "Dogra",
        "NOTES": []
    },
    "Dsrt": {
        "name": "Deseret",
        "NOTES": []
    },
    "Dupl": {
        "name": "Stenografia duployan",
        "NOTES": []
    },
    "Egyd": {
        "name": "Egizio demotico",
        "NOTES": []
    },
    "Egyh": {
        "name": "Egizio ieratico",
        "NOTES": []
    },
    "Egyp": {
        "name": "Egizio geroglifico",
        "NOTES": []
    },
    "Elba": {
        "name": "Elbasan",
        "NOTES": []
    },
    "Elym": {
        "name": "Elimaico",
        "NOTES": []
    },
    "Ethi": {
        "name": "Etiope (Geʻez)",
        "NOTES": []
    },
    "Gara": {
        "name": "Garay",
        "NOTES": []
    },
    "Geok": {
        "name": "Khutsuri (Asomtavruli e Nuskhuri)",
        "NOTES": []
    },
    "Geor": {
        "name": "Georgiano (Mkhedruli e Mtavruli)",
        "NOTES": []
    },
    "Glag": {
        "name": "Glagolitico",
        "NOTES": []
    },
    "Gong": {
        "name": "Gunjala gondi",
        "NOTES": []
    },
    "Gonm": {
        "name": "Masaram gondi",
        "NOTES": []
    },
    "Goth": {
        "name": "Gotico",
        "NOTES": []
    },
    "Gran": {
        "name": "Grantha",
        "NOTES": []
    },
    "Grek": {
        "name": "Greco",
        "NOTES": []
    },
    "Gujr": {
        "name": "Gugiarati (Gujarati)",
        "NOTES": [
            "https://it.wikipedia.org/wiki/Lingua_gujar%C4%81t%C4%AB"
        ]
    },
    "Gukh": {
        "name": "Gurung Khema",
        "NOTES": []
    },
    "Guru": {
        "name": "Gurmukhi",
        "NOTES": []
    },
    "Hanb": {
        "name": "Han con Bopomofo (alias per Han + Bopomofo)",
        "NOTES": []
    },
    "Hang": {
        "name": "Hangul (Hang' l, Hangeul)",
        "NOTES": []
    },
    "Hani": {
        "name": "Han (Hanzi, Kanji, Hanja)",
        "NOTES": []
    },
    "Hano": {
        "name": "Hanunoo (Hanunóo)",
        "NOTES": []
    },
    "Hans": {
        "name": "Han (variante semplificata)",
        "NOTES": []
    },
    "Hant": {
        "name": "Han (variante tradizionale)",
        "NOTES": []
    },
    "Hatr": {
        "name": "Hatrena (Aramaico di Hatra)",
        "NOTES": []
    },
    "Hebr": {
        "name": "Ebraico",
        "NOTES": []
    },
    "Hira": {
        "name": "Hiragana",
        "NOTES": []
    },
    "Hluw": {
        "name": "Geroglifici anatolici (Geroglifici luvi, Geroglifici ittiti)",
        "NOTES": []
    },
    "Hmng": {
        "name": "Pahawh Hmong",
        "NOTES": []
    },
    "Hmnp": {
        "name": "Nyiakeng Puachue Hmong",
        "NOTES": []
    },
    "Hntl": {
        "name": "Han (variante tradizionale) con latino (alias per Hant + Latn)",
        "NOTES": []
    },
    "Hrkt": {
        "name": "Sillabari giapponesi (alias per Hiragana + Katakana)",
        "NOTES": []
    },
    "Hung": {
        "name": "Ungherese antico (runico ungherese)",
        "NOTES": []
    },
    "Inds": {
        "name": "Indo (Harappa)",
        "NOTES": []
    },
    "Ital": {
        "name": "Italico antico (etrusco, osco, ecc...)",
        "NOTES": []
    },
    "Jamo": {
        "name": "Jamo (alias per il sottoinsieme Jamo di Hangul)",
        "NOTES": []
    },
    "Java": {
        "name": "Giavanese",
        "NOTES": [
            "https://it.wikipedia.org/wiki/Lingua_giavanese",
            "https://www.treccani.it/vocabolario/giavanese/"
        ]
    },
    "Jpan": {
        "name": "Giapponese (alias per Han + Hiragana + Katakana)",
        "NOTES": []
    },
    "Jurc": {
        "name": "Jurchen",
        "NOTES": []
    },
    "Kali": {
        "name": "Kayah Li",
        "NOTES": []
    },
    "Kana": {
        "name": "Katakana",
        "NOTES": []
    },
    "Kawi": {
        "name": "Kawi",
        "NOTES": []
    },
    "Khar": {
        "name": "Kharoshthi",
        "NOTES": []
    },
    "Khmr": {
        "name": "Cambogiano (Khmer)",
        "NOTES": []
    },
    "Khoj": {
        "name": "Khojki",
        "NOTES": []
    },
    "Kitl": {
        "name": "Alfabeto Kitai grande",
        "NOTES": []
    },
    "Kits": {
        "name": "Alfabeto Kitai piccolo",
        "NOTES": []
    },
    "Knda": {
        "name": "Canarese (Kannada, Cànara, Kànara)",
        "NOTES": [
            "https://www.treccani.it/vocabolario/canarese/"
        ]
    },
    "Kore": {
        "name": "Coreano (alias per Hangul + Han)",
        "NOTES": []
    },
    "Kpel": {
        "name": "Kpelle",
        "NOTES": []
    },
    "Krai": {
        "name": "Kirat Rai",
        "NOTES": []
    },
    "Kthi": {
        "name": "Kaithi",
        "NOTES": []
    },
    "Lana": {
        "name": "Tai Tham (Lanna)",
        "NOTES": []
    },
    "Laoo": {
        "name": "Laotiano, Laosiano, Laoziano",
        "NOTES": [
            "https://it.wikipedia.org/wiki/Alfabeto_laotiano",
            "https://www.treccani.it/vocabolario/laotiano/"
        ]
    },
    "Latf": {
        "name": "Latino (scrittura Fraktur)",
        "NOTES": []
    },
    "Latg": {
        "name": "Latino (scrittura gaelica)",
        "NOTES": []
    },
    "Latn": {
        "name": "Latino",
        "NOTES": []
    },
    "Leke": {
        "name": "Leke",
        "NOTES": []
    },
    "Lepc": {
        "name": "Lepcha (Róng)",
        "NOTES": []
    },
    "Limb": {
        "name": "Limbu",
        "NOTES": []
    },
    "Lina": {
        "name": "Lineare A",
        "NOTES": []
    },
    "Linb": {
        "name": "Lineare B",
        "NOTES": []
    },
    "Lisu": {
        "name": "Lisu (Fraser)",
        "NOTES": []
    },
    "Loma": {
        "name": "Loma",
        "NOTES": []
    },
    "Lyci": {
        "name": "Licio",
        "NOTES": []
    },
    "Lydi": {
        "name": "Lidio",
        "NOTES": []
    },
    "Mahj": {
        "name": "Mahajani",
        "NOTES": []
    },
    "Maka": {
        "name": "Makasar",
        "NOTES": []
    },
    "Mand": {
        "name": "Mandaico, Mandei",
        "NOTES": [
            "https://it.wikipedia.org/wiki/Lingua_mandaica",
            "https://www.treccani.it/vocabolario/mandaico/"
        ]
    },
    "Mani": {
        "name": "Manicheo",
        "NOTES": []
    },
    "Marc": {
        "name": "Marchen",
        "NOTES": []
    },
    "Maya": {
        "name": "Geroglifici Maya",
        "NOTES": []
    },
    "Medf": {
        "name": "Medefaidrin (Oberi Okaime)",
        "NOTES": []
    },
    "Mend": {
        "name": "Mende Kikakui",
        "NOTES": []
    },
    "Merc": {
        "name": "Corsivo meroitico",
        "NOTES": [
            "https://it.wikipedia.org/wiki/Alfabeto_meroitico",
            "https://www.treccani.it/vocabolario/meroitico/"
        ]
    },
    "Mero": {
        "name": "Geroglifici meroitici",
        "NOTES": []
    },
    "Mlym": {
        "name": "Malayalam",
        "NOTES": [
            "https://it.wikipedia.org/wiki/Lingua_malay%C4%81la%E1%B9%83"
        ]
    },
    "Modi": {
        "name": "Modi",
        "NOTES": []
    },
    "Mong": {
        "name": "Mongolo",
        "NOTES": []
    },
    "Moon": {
        "name": "Moon (codice Moon, scrittura Moon, tipo Moon)",
        "NOTES": []
    },
    "Mroo": {
        "name": "Mro, Mru",
        "NOTES": []
    },
    "Mtei": {
        "name": "Meitei Mayek (Meithei, Meetei)",
        "NOTES": []
    },
    "Mult": {
        "name": "Multani",
        "NOTES": []
    },
    "Mymr": {
        "name": "Birmano (Myanmar)",
        "NOTES": []
    },
    "Nagm": {
        "name": "Nag Mundari",
        "NOTES": []
    },
    "Nand": {
        "name": "Nandinagari",
        "NOTES": []
    },
    "Narb": {
        "name": "Arabo Settentrionale Antico",
        "NOTES": []
    },
    "Nbat": {
        "name": "Nabateo",
        "NOTES": [
            "https://www.treccani.it/vocabolario/nabateo/",
            "https://it.wikipedia.org/wiki/Lingua_nabatea"
        ]
    },
    "Newa": {
        "name": "Newa, Newari, Newar, Nevar, Lipi nepalese",
        "NOTES": []
    },
    "Nkdb": {
        "name": "Naxi Dongba (Nakhi Tomba)",
        "NOTES": []
    },
    "Nkgb": {
        "name": "Naxi Geba (Nakhi Geba)",
        "NOTES": []
    },
    "Nkoo": {
        "name": "N’Ko",
        "NOTES": []
    },
    "Nshu": {
        "name": "Nü shu",
        "NOTES": []
    },
    "Ogam": {
        "name": "Ogham",
        "NOTES": []
    },
    "Olck": {
        "name": "Ol Chiki (Ol Chemet’, Ol, Santali)",
        "NOTES": []
    },
    "Onao": {
        "name": "Ol Onal",
        "NOTES": []
    },
    "Orkh": {
        "name": "Turco antico, Orkhon runico",
        "NOTES": []
    },
    "Orya": {
        "name": "Odia (Oriya)",
        "NOTES": []
    },
    "Osge": {
        "name": "Osage",
        "NOTES": []
    },
    "Osma": {
        "name": "Osmanya, Somalo",
        "NOTES": []
    },
    "Ougr": {
        "name": "Uiguro antico",
        "NOTES": [
            "https://www.treccani.it/enciclopedia/uiguri_(Dizionario-di-Storia)/"
        ]
    },
    "Palm": {
        "name": "Palmireno",
        "NOTES": [
            "https://www.treccani.it/vocabolario/palmireno/"
        ]
    },
    "Pauc": {
        "name": "Pau Cin Hau",
        "NOTES": []
    },
    "Pcun": {
        "name": "Protocuneiforme",
        "NOTES": []
    },
    "Pelm": {
        "name": "Protoelamico",
        "NOTES": []
    },
    "Perm": {
        "name": "Permico antico (Permiano antico)",
        "NOTES": [
            "https://it.wikipedia.org/wiki/Lingue_permiche"
        ]
    },
    "Phag": {
        "name": "'Phags-pa",
        "NOTES": []
    },
    "Phli": {
        "name": "Pahlavi, Pahlevi (iscrizioni)",
        "NOTES": [
            "https://it.wikipedia.org/wiki/Lingua_pahlavi",
            "https://www.treccani.it/enciclopedia/pahlavi_(Dizionario-di-Storia)/"
        ]
    },
    "Phlp": {
        "name": "Pahlavi, Pahlevi (salterio)",
        "NOTES": []
    },
    "Phlv": {
        "name": "Pahlavi, Pahlevi (libro)",
        "NOTES": []
    },
    "Phnx": {
        "name": "Fenicio",
        "NOTES": []
    },
    "Plrd": {
        "name": "Pollard (Miao Pollard)",
        "NOTES": []
    },
    "Piqd": {
        "name": "Klingon (pIqaD)",
        "NOTES": []
    },
    "Prti": {
        "name": "Parto (iscrizioni)",
        "NOTES": []
    },
    "Psin": {
        "name": "Proto-Sinaitico",
        "NOTES": []
    },
    "Qaaa": {
        "name": "Riservato per uso privato (start)",
        "NOTES": []
    },
    "Qabx": {
        "name": "Riservato per uso privato (end)",
        "NOTES": []
    },
    "Ranj": {
        "name": "Ranjana",
        "NOTES": []
    },
    "Rjng": {
        "name": "Rejang (Redjang, Kaganga)",
        "NOTES": []
    },
    "Rohg": {
        "name": "Rohingya hanifi",
        "NOTES": []
    },
    "Roro": {
        "name": "Rongorongo",
        "NOTES": []
    },
    "Runr": {
        "name": "Runico",
        "NOTES": []
    },
    "Samr": {
        "name": "Samaritano",
        "NOTES": []
    },
    "Sara": {
        "name": "Sarati",
        "NOTES": []
    },
    "Sarb": {
        "name": "Arabo meridionale antico",
        "NOTES": []
    },
    "Saur": {
        "name": "Saurashtra",
        "NOTES": []
    },
    "Seal": {
        "name": "Sigillario",
        "NOTES": []
    },
    "Sgnw": {
        "name": "Sutton SignWriting, SignWriting, Scrittura dei segni",
        "NOTES": []
    },
    "Shaw": {
        "name": "Shaviano",
        "NOTES": [
            "https://it.wikipedia.org/wiki/Alfabeto_shaviano"
        ]
    },
    "Shrd": {
        "name": "Sharada, Śāradā, Charada",
        "NOTES": []
    },
    "Shui": {
        "name": "Shuishu, Sui",
        "NOTES": []
    },
    "Sidd": {
        "name": "Siddham, Siddhaṃ, Siddhamātṛkā",
        "NOTES": []
    },
    "Sidt": {
        "name": "Sidetico",
        "NOTES": [
            "https://it.wikipedia.org/wiki/Lingua_sidetica"
        ]
    },
    "Sind": {
        "name": "Khudawadi, Sindhi",
        "NOTES": []
    },
    "Sinh": {
        "name": "Singalese, Cingalese, Ceylonese, Silonense, Sinhala",
        "NOTES": [
            "https://it.wikipedia.org/wiki/Lingua_singalese",
            "https://www.treccani.it/vocabolario/singalese/",
            "https://www.treccani.it/vocabolario/ceylonense/"
        ]
    },
    "Sogd": {
        "name": "Sogdian",
        "NOTES": []
    },
    "Sogo": {
        "name": "Sogdiano antico",
        "NOTES": [
            "https://it.wikipedia.org/wiki/Alfabeto_sogdiano"
        ]
    },
    "Sora": {
        "name": "Sora Sompeng",
        "NOTES": []
    },
    "Soyo": {
        "name": "Soyombo",
        "NOTES": []
    },
    "Sund": {
        "name": "Sundanese, Sondanese",
        "NOTES": [
            "https://www.treccani.it/vocabolario/sundanese/",
            "https://it.wikipedia.org/wiki/Lingua_sundanese"
        ]
    },
    "Sunu": {
        "name": "Sunuwar",
        "NOTES": []
    },
    "Sylo": {
        "name": "Sylheti, Sileṭ Nagri",
        "NOTES": []
    },
    "Syrc": {
        "name": "Siriaco",
        "NOTES": []
    },
    "Syre": {
        "name": "Siriaco (variante ʾEsṭrangēlā)",
        "NOTES": []
    },
    "Syrj": {
        "name": "Siriaco (variante occidentale)",
        "NOTES": []
    },
    "Syrn": {
        "name": "Siriaco (variante orientale)",
        "NOTES": []
    },
    "Tagb": {
        "name": "Tagbanwa, Aborlan Tagbanwa, Apurawnon",
        "NOTES": []
    },
    "Takr": {
        "name": "Takri",
        "NOTES": []
    },
    "Tale": {
        "name": "Tai Le",
        "NOTES": []
    },
    "Talu": {
        "name": "Nuovo Tai lue, Tai lue semplificato",
        "NOTES": []
    },
    "Taml": {
        "name": "Tàmil, Tàmul",
        "NOTES": []
    },
    "Tang": {
        "name": "Tangut",
        "NOTES": []
    },
    "Tavt": {
        "name": "Tai Viet",
        "NOTES": []
    },
    "Tayo": {
        "name": "Tai Yo",
        "NOTES": []
    },
    "Telu": {
        "name": "Tèlugu",
        "NOTES": []
    },
    "Teng": {
        "name": "Tengwar",
        "NOTES": []
    },
    "Tfng": {
        "name": "Tifinagh (Berbero)",
        "NOTES": []
    },
    "Tglg": {
        "name": "Tagalog, Tagalo",
        "NOTES": []
    },
    "Thaa": {
        "name": "Thaana, Taana, Tāna",
        "NOTES": []
    },
    "Thai": {
        "name": "Tailandese",
        "NOTES": []
    },
    "Tibt": {
        "name": "Tibetano",
        "NOTES": []
    },
    "Tirh": {
        "name": "Tirhuta",
        "NOTES": []
    },
    "Tnsa": {
        "name": "Tangsa",
        "NOTES": []
    },
    "Todr": {
        "name": "Todhri",
        "NOTES": []
    },
    "Tols": {
        "name": "Tolong Siki",
        "NOTES": []
    },
    "Toto": {
        "name": "Toto",
        "NOTES": []
    },
    "Tutg": {
        "name": "Tigalari, Tulu",
        "NOTES": []
    },
    "Ugar": {
        "name": "Ugaritico",
        "NOTES": [
            "https://it.wikipedia.org/wiki/Alfabeto_ugaritico",
            "https://www.treccani.it/vocabolario/ugaritico/"
        ]
    },
    "Vaii": {
        "name": "Vai",
        "NOTES": []
    },
    "Visp": {
        "name": "Discorso visibile",
        "NOTES": []
    },
    "Vith": {
        "name": "Vithkuqi, Büthakukye, Beitha Kukju",
        "NOTES": []
    },
    "Wara": {
        "name": "Warang Chiti (Varang Kshiti)",
        "NOTES": []
    },
    "Wcho": {
        "name": "Wancho",
        "NOTES": []
    },
    "Wole": {
        "name": "Woleai",
        "NOTES": []
    },
    "Xpeo": {
        "name": "Persiano antico",
        "NOTES": []
    },
    "Xsux": {
        "name": "Cuneiforme, Sumero-Accadico",
        "NOTES": []
    },
    "Yezi": {
        "name": "Yezidi",
        "NOTES": []
    },
    "Yiii": {
        "name": "Yi",
        "NOTES": []
    },
    "Zanb": {
        "name": "Zanabazar quadrato (Scrittura Orizontale Quadrata)",
        "NOTES": []
    },
    "Zinh": {
        "name": "Codice per script ereditato",
        "NOTES": []
    },
    "Zmth": {
        "name": "Notazione matematica",
        "NOTES": []
    },
    "Zsye": {
        "name": "Simboli (variante Emoji)",
        "NOTES": []
    },
    "Zsym": {
        "name": "Simboli",
        "NOTES": []
    },
    "Zxxx": {
        "name": "Codice per documenti non scritti",
        "NOTES": []
    },
    "Zyyy": {
        "name": "Codice per script indeterminato",
        "NOTES": []
    },
    "Zzzz": {
        "name": "Codice per script non codificato",
        "NOTES": []
    }
}`